"""empty message

Revision ID: 3dea3e06eac3
Revises: eee1928a051c
Create Date: 2021-04-09 21:55:41.501226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dea3e06eac3'
down_revision = 'eee1928a051c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea', 'created')
    # ### end Alembic commands ###
