"""empty message

Revision ID: eee1928a051c
Revises: d038d2bdedcb
Create Date: 2021-03-28 16:32:03.251635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee1928a051c'
down_revision = 'd038d2bdedcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('idea') as batch_op:
        batch_op.drop_column('pluses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('pluses', sa.INTEGER(), nullable=False))
    op.drop_column('idea', 'created')
    # ### end Alembic commands ###
